#!/usr/bin/with-contenv bash
# shellcheck shell=bash

export \
    ANI_AR_REMOTE_REVISION_RAW_URL="https://gist.githubusercontent.com/mohammedahmed18/08527c7de57cd8d5c027f22ae929f750/raw/ani-ar-for-jellyfin-list.json" \
    ANI_AR_ANIME_SHOWS_FOLDER_PATH="/app/media/anime-shows/" \
    ANI_AR_ANIME_MOVIES_FOLDER_PATH="/app/media/anime-movies/"

mkdir -p $ANI_AR_ANIME_SHOWS_FOLDER_PATH $ANI_AR_ANIME_MOVIES_FOLDER_PATH

exec ani-ar jelly

